# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Weather.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(470, 235)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_name = QtWidgets.QLineEdit(self.centralwidget)
        self.input_name.setGeometry(QtCore.QRect(110, 10, 231, 51))
        self.input_name.setObjectName("input_name")
        self.btn_Wea = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Wea.setGeometry(QtCore.QRect(350, 10, 111, 41))
        self.btn_Wea.setObjectName("btn_Wea")
        self.lbl_tmp = QtWidgets.QLabel(self.centralwidget)
        self.lbl_tmp.setGeometry(QtCore.QRect(10, 80, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_tmp.setFont(font)
        self.lbl_tmp.setText("")
        self.lbl_tmp.setObjectName("lbl_tmp")
        self.lbl_emoji = QtWidgets.QLabel(self.centralwidget)
        self.lbl_emoji.setGeometry(QtCore.QRect(340, 70, 118, 84))
        self.lbl_emoji.setMinimumSize(QtCore.QSize(118, 76))
        self.lbl_emoji.setMaximumSize(QtCore.QSize(115, 84))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_emoji.setFont(font)
        self.lbl_emoji.setText("")
        self.lbl_emoji.setObjectName("lbl_emoji")
        self.lbl_des = QtWidgets.QLabel(self.centralwidget)
        self.lbl_des.setGeometry(QtCore.QRect(130, 80, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lbl_des.setFont(font)
        self.lbl_des.setText("")
        self.lbl_des.setObjectName("lbl_des")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 470, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_Wea.setText(_translate("MainWindow", "Get Weather"))
        self.lbl_emoji.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:48pt;\">😂</span></p></body></html>"))
